- name: Deploy app to EC2
  hosts: all
  become: true

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy HTML file
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Start nginx
      service:
        name: nginx
        state: started
