pipeline {
    agent any

    stages {
        stage("Run Ansible Playbook") {
            steps {
                withCredentials([
                    sshUserPrivateKey(
                        credentialsId: 'd2bfcac2-1f06-4f5a-a84f-f8cadab827a0',
                        keyFileVariable: 'private_key'
                    )
                ]) {
                    sh '''
                    mkdir -p ~/.ssh
                    chmod 700 ~/.ssh

                    ssh-keygen -R 18.207.126.240 || true
                    ssh-keygen -R 54.145.6.120 || true

                    ssh-keyscan -H 18.207.126.240 >> ~/.ssh/known_hosts
                    ssh-keyscan -H 54.145.6.120 >> ~/.ssh/known_hosts

                    chmod 600 ~/.ssh/known_hosts
                    '''

                    dir('activity_2') {
                        sh '''
                        ansible-playbook -i inventory deploy.yml --private-key $private_key -u ubuntu
                        '''
                    }
                }
            }
        }
    }
}